name=LongLiveThEEPROM
version=0.0.1
author=Volodymyr Mykhalchuk
maintainer=Volodymyr Mykhalchuk <vmykhalchuk@gmail.com>
sentence=Library to simplify storing Preferences into EEPROM and significantly reduce EEPROM wear
paragraph=Distributes wear over whole EEPROM available, increases lifespan from 100K writes to ~51M writes. Simple to use: PrefOneByte pref; uint8_t p = pref.load(); pref.save(p);
category=Data Storage
url=https://github.com/vmykhalchuk/LongLiveThEEPROM
architectures=avr
license=Apache-2.0